name: 'Roll'
description: 'Rolls for initiative'
inputs:
  title:
    description: 'Github issue title'
    required: true
  user:
    description: 'Github user'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
