on:
  issues:
    types: [opened]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'roll|')
    steps:
      - name: Set env vars
        run: |
          echo ::set-env name=REPOSITORY::${{ github.repository }}
          echo ::set-env name=EVENT_ISSUE_NUMBER::${{ github.event.issue.number }}
          echo ::set-env name=EVENT_USER_LOGIN::${{ github.event.issue.user.login }}
      - uses: actions/checkout@v2
      - name: Roll For Initiative
        uses: /.github/roll
        id: roll
        with:
          title: ${{ github.event.issue.title }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: ${{ github.event.issue.title }}
          title: ${{ github.event.issue.title }}
          body: |
            Closes #${{ github.event.issue.number }}
          labels: automated pr
          branch: roll-for-initiative-${{ github.event.issue.number }}
