on:
  issues:
    types: [opened]

jobs:
  roll_for_initiative:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'roll|')
    steps:
      - name: Set env vars
        run: |
          echo ::set-env name=REPOSITORY::${{ github.repository }}
          echo ::set-env name=EVENT_ISSUE_NUMBER::${{ github.event.issue.number }}
          echo ::set-env name=EVENT_USER_LOGIN::${{ github.event.issue.user.login }}
        
